server:
  port: 9003
spring:
  application:
    name: product-service

  datasource:
    url: jdbc:postgresql://host.docker.internal:49153/postgres
    username: postgres
    password: postgrespw
    driverClassName: org.postgresql.Driver
  batch:
    job:
      enabled: false
  jpa:
    properties:
      format_sql: true
      show-sql: true
    hibernate:
      ddl-auto: create-drop

