server:
  port: 1003
spring:
  application:
    name: product-service
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  batch:
    job:
      enabled: false
  jpa:
    properties:
      format_sql: true
      show-sql: true

